name: Release a new version

on:
  push:
    tags:
      - v0.*
      - v1.*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Install rust toolchain
        shell: bash
        run: rustup set profile minimal; rustup update && rustup component add rustfmt clippy
      
      - name: cargo build
        shell: bash
        run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: "elgato-control-center"
          path: "target/release/elgato-control-center"
