name: Run tests

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust toolchain
        shell: bash
        run: rustup set profile minimal; rustup update && rustup component add rustfmt clippy
      
      - name: cargo fmt
        shell: bash
        run: cargo fmt -- --check
      
      - name: cargo clippy
        shell: bash
        run: cargo clippy -- -D warnings
      
      - name: cargo test
        shell: bash
        run: cargo test
